added define-parms, cleaned up

diff --git a/install-tools b/install-tools
--- a/install-tools
+++ b/install-tools
@@ -44,6 +44,11 @@ if [ ! -d "$BINDIR" ] ; then
     echo "$PROG: $BINDIR is not a directory" >&2
     exit 1
 fi
+mkdir -p "${BINDIR}/lib"
+if [ ! -d "${BINDIR}/lib" ] ; then
+    echo "$PROG: unable to create ${BINDIR}/lib directory" >&2
+    exit 1
+fi
 
 nfail=0
 SCRIPTLIST=`cat ${SCRIPTDIR}/.scriptlist`
